// <auto-generated />
namespace LaTiendaIs2021.DatosV1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class versiof : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(versiof));
        
        string IMigrationMetadata.Id
        {
            get { return "202202220419427_versiof"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
